name: Lint

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v5

      - name: Node.js install
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: Package install
        run: npm ci

      - name: Start ESLint
        run: npm run lint
